### ISSUE TITLE
Tipografia (tamaños) y espacios 

### ISSUE THREAD

**Issue by aixancura** [HernanPeinetti/MercadoLiebre-HernanPeinetti#4]
- El tamaño de la tipografía es muy grande (footer y en el header).
- En sección ofertas el título habría que modificarlo.
- En los artículos agrandar la parte de la descripción dándole un espacio entre el precio, descuento y nombre del producto.

**Comment by HernanPeinetti** [comment]
La mayoría de las tipografías fueron medidos para que sea vea bien tanto en la vista Desktop y Mobile. Los artículos fueron agrandados un poco mas! Gracias por la sugerencia.
